/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_IBV_MLX4_BUF_ALLOCATORS

#define HAVE_IBV_MLX4_UAR_MMAP_OFFSET

#define HAVE_IBV_MLX4_WQE_LSO_SEG

