load("@rules_cc//cc:defs.bzl", "cc_library")
load("//:generate_h.bzl", "make_ch_genrules")
load("//:generate_macros.bzl", "gen_filtered_macros")
load("//:generate_rte_config.bzl", "generate_build_config")

gen_filtered_macros(
    name = "filtered_predefined_macros",
)

make_ch_genrules(
    script = "freebsd/tools/makeobjops.awk",
    h_files = [
        "freebsd/kern/bus_if.m",
        "freebsd/kern/device_if.m",
        "freebsd/kern/linker_if.m",
        "freebsd/opencrypto/cryptodev_if.m",
    ],
    c_files = [
        "freebsd/kern/linker_if.m",
        "freebsd/opencrypto/cryptodev_if.m",
    ],
)

make_ch_genrules(
    script = "freebsd/tools/vnode_if.awk",
    h_files = ["freebsd/kern/vnode_if.src"],
    typedef_files = ["freebsd/kern/vnode_if.src"],
    newproto_files = ["freebsd/kern/vnode_if.src"],
)

cc_library(
    name = "x86",
    hdrs = glob(
        include = [
            "freebsd/x86/include/**/*.h",
        ],
    ),
    includes = [
        "freebsd/x86/include",
    ],
    strip_include_prefix = "freebsd/x86/include",
    include_prefix = "x86",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "machine",
    includes = [
        "freebsd/amd64/include",
    ],
    hdrs = glob(
        include = [
            "freebsd/amd64/include/**/*.h",
        ],
    ),
    strip_include_prefix = "freebsd/amd64/include",
    include_prefix = "machine",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "lib-stdinc",
    srcs = glob(
        include = [
            "lib/ff_dpdk_if.c",
            "lib/ff_host_interface.c",
            "lib/ff_thread.c",
            "lib/ff_config.c",
            "lib/ff_ini_parser.c",
            "lib/ff_dpdk_if.c",
            "lib/ff_dpdk_pcap.c",
            "lib/ff_epoll.c",
            "lib/ff_init.c",
            "lib/ff_dpdk_kni.c",
            "lib/*.h",
         ],
    ),
    deps = [
        ":dpdk",
        "@openssl//:crypto",
    ],
    defines = [
        "__FBSDID(x)=",
    ],
    copts = [
        "-mrtm",
        "-mavx512f", "-mavx512dq", "-mavx512bw", "-mavx512vl", "-mavx512ifma",
        "-mavx512er", "-mavx512cd", "-mavx2", "-mavx", "-msse4.2", "-msse4.1",
        "-mvpclmulqdq",
    ],
)

cc_library(
    name = "lib-nostdinc",
    srcs = glob(
        include = [
            "lib/**/*.c",
            "lib/**/*.h",
            "freebsd/**/*.h",
         ],
         exclude = [
            "lib/ff_dpdk_if.c",
            "lib/ff_host_interface.c",
            "lib/ff_thread.c",
            "lib/ff_config.c",
            "lib/ff_ini_parser.c",
            "lib/ff_dpdk_if.c",
            "lib/ff_dpdk_pcap.c",
            "lib/ff_epoll.c",
            "lib/ff_init.c",
            "lib/ff_dpdk_kni.c",
            "lib/ff_memory.c",
         ],
    ) + [
        ":bus_if_h_generated",
        ":cryptodev_if_c_generated",
        ":cryptodev_if_h_generated",
        ":device_if_h_generated",
        ":linker_if_c_generated",
        ":linker_if_h_generated",
        ":vnode_if_h_generated",
        ":vnode_if_p_generated",
        ":vnode_if_q_generated",
        ":filtered_predefined_macros",
    ],
    deps = [
        ":x86",
        ":machine",
        "@openssl//:crypto",
        # "@openssl//:generated-headers",
    ],
    defines = [
        "INET",
        "INET6",
        "TCPHPTS",
        "RATELIMIT",
        "FSTACK",
        "__FreeBSD__",
        "_KERNEL",
        "HAVE_KERNEL_OPTION_HEADERS",
    ],
    copts = [
        "-O2",
        "-fno-strict-aliasing",
        # "-frename-registers",
        "-pipe",
        # "-Wno-maybe-uninitialized",
        "-Wno-strict-prototypes",
        "-Wno-source-mgr",
        "-std=c99",
        "-Wall",
        "-Wnested-externs",
        # "-Wstrict-prototypes",
        "-Wmissing-prototypes",
        "-Wpointer-arith",
        "-Wno-inline",
        "-Wcast-qual",
        "-Wno-pointer-sign",
        "-Wno-array-bounds",
        "-Wmissing-include-dirs",
        "-fdiagnostics-show-option",
        "-Wno-unused-but-set-variable",
        "-Wno-address-of-packed-member",
        "-Wno-missing-include-dirs",
        "-fno-common",
        "-DINET",
        "-DINET6",
        "-DTCPHPTS",
        "-DRATELIMIT",
        "-DFSTACK",
        "-D__FreeBSD__",
        "-D_KERNEL",
        "-DHAVE_KERNEL_OPTION_HEADERS",
        "-fstack-protector",
        "-fno-builtin",
        "-include", "lib/opt/opt_global.h",
        "-Ilib/include",
        "-Ifreebsd",
        "-Ilib",
        "-I./freebsd/contrib/ck/include",
        "-I./lib/opt",
        "-undef",
        "-imacros", "lib/filtered_predefined_macros.h",
        "-nostdinc",
        "-Werror",
        "-Wno-unused-variable",
    ],
)

generate_build_config(
    name = "generate_build_config",
    template = "rte_build_config.tpl",
    out = "dpdk/config/rte_build_config.h",
    is_linux = True,
    arch = "x86_64",
    arch_64 = True,
    
    # Common DPDK settings
    max_ethports = "32",
    pkt_mbuf_headroom = "128",
    
    # Version from your project
    ver_year = "23", 
    ver_month = "11",
    ver_minor = "0",
    use_libbsd = False,
)

cc_library(
    name = "config",
    defines = [
        "ALLOW_EXPERIMENTAL_API",
        "ALLOW_INTERNAL_API",
        "_GNU_SOURCE",
        "ABI_VERSION=\\\"23.07\\\"",
        "RTE_ARCH_X86=1",
        "TAP_MAX_QUEUES=64",
    ],
    hdrs = [
        "dpdk/config/rte_config.h",
        ":generate_build_config",  # Include the generated header
    ],
    includes = ["dpdk/config"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "dpdk",
    srcs = glob(
        include = [
            "dpdk/drivers/**/*.c",
            "dpdk/drivers/**/*.h",
            "dpdk/lib/**/*.c", 
            "dpdk/lib/**/*.h",
        ],
        exclude = [
            "dpdk/**/*_neon.c",
            "dpdk/**/*_neon.h",
            "dpdk/**/*_altivec.c",
            "dpdk/drivers/net/virtio/virtio_rxtx_simple.c",
            # "drivers/net/virtio/virtio_rxtx_simple_sse.c",
            "dpdk/drivers/net/virtio/virtio_rxtx_packed.c",
            "dpdk/drivers/net/mlx5/mlx5_rxtx_vec_null.c",
            "dpdk/drivers/net/mlx5/mlx5_flow_hw_stubs.c",
            "dpdk/drivers/common/mlx5/windows/**",
            "dpdk/drivers/net/mlx5/windows/**",
            "dpdk/drivers/event/dlb2/dlb2_sse.c",
            "dpdk/drivers/net/enic/enic_main.c",
            "dpdk/drivers/net/nfp/nfdk/nfp_nfdk_vec_stub.c",
            "dpdk/drivers/net/nfp/nfp_rxtx_vec_stub.c",

            "dpdk/drivers/net/mvneta/**",
            "dpdk/drivers/net/mvpp2/**",
            "dpdk/drivers/net/sfc/**",
            "dpdk/drivers/net/tap/**",
            "dpdk/drivers/net/qede/**",
            "dpdk/drivers/net/ntnic/**",
            "dpdk/drivers/net/nfb/**",
            "dpdk/drivers/net/bnxt/**",
            "dpdk/drivers/net/hns3/**",
            "dpdk/drivers/net/intel/ice/**",
            "dpdk/drivers/net/intel/cpfl/**",
            "dpdk/drivers/net/pcap/**",
            "dpdk/drivers/raw/ifpga/**",
            "dpdk/drivers/ml/**",
            "dpdk/drivers/compress/isal/**",
            "dpdk/drivers/compress/qat/**",
            "dpdk/drivers/crypto/**",
            "dpdk/drivers/crypto/ipsec_mb/**",
            "dpdk/drivers/crypto/mvsam/**",
            "dpdk/drivers/crypto/armv8/**",
            "dpdk/drivers/power/amd_uncore/**",
            "dpdk/drivers/gpu/cuda/**",
            "dpdk/drivers/common/dpaax/dpaax_logs.h",
            "dpdk/drivers/common/mvep/**",
            "dpdk/drivers/bus/**",
            "dpdk/drivers/bus/fslmc/qbman/qbman_debug.c",
            "dpdk/drivers/bus/pci/bsd/pci.c",
            "dpdk/drivers/bus/pci/windows/**",
            "dpdk/drivers/net/pcap/pcap_osdep_windows.c",
            "dpdk/lib/distributor/rte_distributor_match_generic.c",
            "dpdk/lib/eal/linux/vduse.h", # vduse.h is not used in the build
            "dpdk/lib/vhost/vduse.c",
            "dpdk/lib/bpf/bpf_stub.c",
            "dpdk/lib/acl/rte_acl.c",
            "dpdk/lib/acl/acl_run_altivec.c",  # PPC specific
            # "lib/acl/acl_run_altivec.h",  # x86 specific
            "dpdk/lib/acl/acl_run_neon.c", # ARM specific
            "dpdk/lib/acl_run_altivec.c",  # PPC_64 specific
            "dpdk/lib/acl/acl_run_neon.h", # ARM specific
            "dpdk/lib/mldev/mldev_utils_neon.c", # ARM specific
            "dpdk/lib/mldev/mldev_utils_neon.h", # ARM specific
            "dpdk/lib/mldev/mldev_utils_neon_bfloat16.c", # ARM specific
            "dpdk/lib/mldev/mldev_utils_neon_bfloat16.h", # ARM specific
            "dpdk/lib/net/crc_neon.c", # ARM specific
            "dpdk/lib/net/crc_neon.h", # ARM specific
            "dpdk/lib/net/net_crc_neon.c", # ARM specific
            "dpdk/lib/net/net_crc_neon.h", # ARM specific
            "dpdk/lib/eal/arm/**",
            "dpdk/lib/eal/windows/**",
            "dpdk/drivers/bus/fslmc/qbman/qbman_debug.c",
            "dpdk/lib/eal/freebsd/**",
            "dpdk/lib/eal/loongarch/**",
            "dpdk/lib/eal/ppc/**",
            "dpdk/lib/eal/riscv/**",
            "dpdk/lib/cmdline/cmdline_os_windows.c",
        ]
    ),
    hdrs = glob([
        "dpdk/drivers/**/*.h",
        "dpdk/lib/**/*.h",
        "dpdk/app/test-pmd/**/*.h",
    ]),
    deps = [
        ":config",
        "@com_github_rdma//:mlx5dv",
        "@com_github_libelf//:libelf",
        "@com_github_libpcap//:libpcap",
        "@com_github_libbpf//:libbpf",
        "@com_github_libbpf//:libbpf_path",
        "@com_github_libxdp//:libxdp",
        "@com_github_zlib//:zlib",
        "@com_github_uadk//:uadk",
        "@com_github_numactl//:numactl",
    ],
    includes = [
        "dpdk/app/test-pmd",
        "dpdk/drivers/net/intel/ixgbe",
        "dpdk/drivers/raw/ifpga",
        "dpdk/drivers/net/intel/i40e/",
        "dpdk/drivers/net/bnxt/hcapi/cfa_v3/tim/include",
        "dpdk/drivers/net",
        "dpdk/drivers/net/tap",
        "dpdk/drivers/net/virtio",
        "dpdk/drivers/net/intel/iavf",
        "dpdk/drivers/net/mlx5",
        "dpdk/drivers/net/mlx5/linux/",
        "dpdk/drivers/net/ntnic/nthw/flow_api",
        "dpdk/drivers/net/ntnic",
        "dpdk/drivers/net/bnxt/hcapi/cfa_v3/bld/include",
        "dpdk/drivers/net/bnxt/hcapi/cfa_v3/bld/include/host",
        "dpdk/drivers/net/bnxt/tf_ulp/generic_templates",
        "dpdk/drivers/net/bnxt/hcapi/cfa_v3/include",
        "dpdk/drivers/net/nfb",
        "dpdk/drivers/net/pfe/base",
        "dpdk/drivers/net/bnxt",
        "dpdk/drivers/net/ngbe/base",
        "dpdk/drivers/net/octeontx",
        "dpdk/drivers/net/bnxt/tf_core/v3",
        "dpdk/drivers/net/ntnic/nthw/supported",
        "dpdk/drivers/net/bnxt/hcapi/cfa",
        "dpdk/drivers/net/gve/base",
        "dpdk/drivers/net/nfp",
        "dpdk/drivers/net/ntnic/nthw/model",
        "dpdk/drivers/net/bonding",
        "dpdk/drivers/net/pfe",
        "dpdk/drivers/net/ena/base/ena_defs",
        "dpdk/drivers/net/enic/base",
        "dpdk/drivers/net/bnxt/tf_core",
        "dpdk/drivers/net/dpaa2/mc",
        "dpdk/drivers/net/intel/iavf/base",
        "dpdk/drivers/net/dpaa2",
        "dpdk/drivers/common/dpaax",
        "dpdk/drivers/net/dpaa",
        "dpdk/drivers/net/ntnic/nthw/core/include",
        "dpdk/drivers/net/enic",
        "dpdk/drivers/net/ena/base",
        "dpdk/lib/eal/linux/",
        "dpdk/drivers/net/ntnic/ntutil",
        "dpdk/drivers",
        "dpdk/drivers/ml",
        "dpdk/drivers/ml/cnxk",
        "dpdk/drivers/event",
        "dpdk/drivers/net/ntnic/nthw",
        "dpdk/drivers/event/octeontx",
        "dpdk/drivers/event/dpaa2",
        "dpdk/drivers/event/skeleton",
        "dpdk/drivers/event/sw",
        "dpdk/drivers/event/dsw",
        "dpdk/drivers/event/dpaa",
        "dpdk/drivers/event/dlb2",
        "dpdk/drivers/event/dlb2/pf",
        "dpdk/drivers/event/dlb2/pf/base",
        "dpdk/drivers/event/opdl",
        "dpdk/drivers/event/cnxk",
        "dpdk/drivers/event/cnxk/deq",
        "dpdk/drivers/event/cnxk/deq/cn20k",
        "dpdk/drivers/event/cnxk/deq/cn9k",
        "dpdk/drivers/event/cnxk/deq/cn10k",
        "dpdk/drivers/event/cnxk/tx",
        "dpdk/drivers/event/cnxk/tx/cn20k",
        "dpdk/drivers/event/cnxk/tx/cn9k",
        "dpdk/drivers/event/cnxk/tx/cn10k",
        "dpdk/drivers/net/gve",
        "dpdk/drivers/net/cnxk",
        "dpdk/drivers/net/bnxt/tf_ulp",
        "dpdk/drivers/net/intel/idpf",
        "dpdk/drivers/net/ntnic/ntlog",
        "dpdk/drivers/net/ntnic/include",
        "dpdk/drivers/power",
        "dpdk/drivers/power/amd_uncore",
        "dpdk/drivers/power/kvm_vm",
        "dpdk/drivers/power/amd_pstate",
        "dpdk/drivers/power/intel_uncore",
        "dpdk/drivers/power/intel_pstate",
        "dpdk/drivers/power/cppc",
        "dpdk/drivers/power/acpi",
        "dpdk/drivers/vdpa",
        "dpdk/drivers/vdpa/ifc",
        "dpdk/drivers/vdpa/ifc/base",
        "dpdk/drivers/vdpa/sfc",
        "dpdk/drivers/vdpa/mlx5",
        "dpdk/drivers/vdpa/nfp",
        "dpdk/drivers/common",
        "dpdk/drivers/common/sfc_efx",
        "dpdk/drivers/common/sfc_efx/base",
        "dpdk/drivers/common/mvep",
        "dpdk/drivers/common/octeontx",
        "dpdk/drivers/common/dpaax/caamflib",
        "dpdk/drivers/common/dpaax/caamflib/desc",
        "dpdk/drivers/common/dpaax/caamflib/rta",
        "dpdk/drivers/common/zsda",
        "dpdk/drivers/common/mlx5",
        "dpdk/drivers/common/mlx5/linux",
        "dpdk/drivers/common/ionic",
        "dpdk/drivers/common/qat",
        "dpdk/drivers/common/qat/qat_adf",
        "dpdk/drivers/common/qat/dev",
        "dpdk/drivers/common/cpt",
        "dpdk/drivers/common/cnxk",
        "dpdk/drivers/common/cnxk/hw",
        "dpdk/drivers/common/nfp",
        "dpdk/drivers/common/nitrox",
        "dpdk/drivers/bus",
        "dpdk/drivers/bus/cdx",
        "dpdk/drivers/bus/uacce",
        "dpdk/drivers/bus/auxiliary",
        "dpdk/drivers/bus/auxiliary/linux",
        "dpdk/drivers/bus/pci",
        "dpdk/drivers/bus/pci/bsd",
        "dpdk/drivers/bus/pci/linux",
        "dpdk/drivers/bus/platform",
        "dpdk/drivers/bus/dpaa",
        "dpdk/drivers/bus/dpaa/include",
        "dpdk/drivers/bus/dpaa/base",
        "dpdk/drivers/bus/dpaa/base/qbman",
        "dpdk/drivers/bus/dpaa/base/fman",
        "dpdk/drivers/bus/ifpga",
        "dpdk/drivers/bus/vdev",
        "dpdk/drivers/bus/vmbus",
        "dpdk/drivers/bus/vmbus/linux",
        "dpdk/drivers/bus/fslmc",
        "dpdk/drivers/bus/fslmc/qbman",
        "dpdk/drivers/bus/fslmc/qbman/include",
        "dpdk/drivers/bus/fslmc/mc",
        "dpdk/drivers/bus/fslmc/portal",
        "dpdk/drivers/regex",
        "dpdk/drivers/regex/cn9k",
        "dpdk/drivers/regex/mlx5",
        "dpdk/drivers/raw",
        "dpdk/drivers/raw/cnxk_bphy",
        "dpdk/drivers/raw/cnxk_rvu_lf",
        "dpdk/drivers/raw/dpaa2_cmdif",
        "dpdk/drivers/raw/skeleton",
        "dpdk/drivers/raw/gdtc",
        "dpdk/drivers/raw/cnxk_gpio",
        "dpdk/drivers/raw/ntb",
        "dpdk/drivers/baseband",
        "dpdk/drivers/baseband/null",
        "dpdk/drivers/baseband/la12xx",
        "dpdk/drivers/baseband/fpga_lte_fec",
        "dpdk/drivers/baseband/turbo_sw",
        "dpdk/drivers/baseband/acc",
        "dpdk/drivers/baseband/fpga_5gnr_fec",
        "dpdk/drivers/compress",
        "dpdk/drivers/compress/octeontx",
        "dpdk/drivers/compress/octeontx/include",
        "dpdk/drivers/compress/zsda",
        "dpdk/drivers/compress/mlx5",
        "dpdk/drivers/compress/qat",
        "dpdk/drivers/compress/qat/dev",
        "dpdk/drivers/compress/uadk",
        "dpdk/drivers/compress/nitrox",
        "dpdk/drivers/compress/zlib",
        "dpdk/drivers/crypto",
        "dpdk/drivers/crypto/openssl",
        "dpdk/drivers/crypto/null",
        "dpdk/drivers/crypto/scheduler",
        "dpdk/drivers/crypto/armv8",
        "dpdk/drivers/crypto/octeontx",
        "dpdk/drivers/crypto/ccp",
        "dpdk/drivers/crypto/mvsam",
        "dpdk/drivers/crypto/bcmfs",
        "dpdk/drivers/crypto/bcmfs/hw",
        "dpdk/drivers/crypto/dpaa2_sec",
        "dpdk/drivers/crypto/dpaa2_sec/mc",
        "dpdk/drivers/crypto/caam_jr",
        "dpdk/drivers/crypto/mlx5",
        "dpdk/drivers/crypto/ionic",
        "dpdk/drivers/crypto/qat",
        "dpdk/drivers/crypto/qat/dev",
        "dpdk/drivers/crypto/ipsec_mb",
        "dpdk/drivers/crypto/virtio",
        "dpdk/drivers/crypto/virtio/virtio_user",
        "dpdk/drivers/crypto/uadk",
        "dpdk/drivers/crypto/dpaa_sec",
        "dpdk/drivers/crypto/cnxk",
        "dpdk/drivers/crypto/nitrox",
        "dpdk/drivers/dma",
        "dpdk/drivers/dma/dpaa2",
        "dpdk/drivers/dma/skeleton",
        "dpdk/drivers/dma/odm",
        "dpdk/drivers/dma/idxd",
        "dpdk/drivers/dma/hisilicon",
        "dpdk/drivers/dma/dpaa",
        "dpdk/drivers/dma/cnxk",
        "dpdk/drivers/dma/ioat",
        "dpdk/drivers/ml/cnxk",
        "dpdk/drivers/mempool",
        "dpdk/drivers/mempool/ring",
        "dpdk/drivers/mempool/octeontx",
        "dpdk/drivers/mempool/dpaa2",
        "dpdk/drivers/mempool/bucket",
        "dpdk/drivers/mempool/stack",
        "dpdk/drivers/mempool/dpaa",
        "dpdk/drivers/mempool/cnxk",
        "dpdk/drivers/gpu",
        "dpdk/drivers/gpu/cuda",
        # libs
        "dpdk/lib/eal/common",
        "dpdk/lib/eal/include",
        "dpdk/lib/eal/linux/include",
        "dpdk/lib/eal/x86/include",
        "dpdk/lib/eal/include/generic",
        "dpdk/lib/log",
        "dpdk/lib/kvargs", # eal depends on kvargs
        "dpdk/lib/argparse",
        "dpdk/lib/telemetry", # basic info querying
        "dpdk/lib/ptr_compress",
        "dpdk/lib/ring",
        "dpdk/lib/rcu", # rcu depends on ring
        "dpdk/lib/mempool",
        "dpdk/lib/mbuf",
        "dpdk/lib/net",
        "dpdk/lib/meter",
        "dpdk/lib/ethdev",
        "dpdk/lib/pci", # core
        "dpdk/lib/cmdline",
        "dpdk/lib/metrics", # bitrate/latency stats depends on this
        "dpdk/lib/hash",    # efd depends on this
        "dpdk/lib/timer",   # eventdev depends on this
        "dpdk/lib/acl",
        "dpdk/lib/bbdev",
        "dpdk/lib/bitratestats",
        "dpdk/lib/bpf",
        "dpdk/lib/cfgfile",
        "dpdk/lib/compressdev",
        "dpdk/lib/cryptodev",
        "dpdk/lib/distributor",
        "dpdk/lib/dmadev",  # eventdev depends on this
        "dpdk/lib/efd",
        "dpdk/lib/eventdev",
        "dpdk/lib/dispatcher", # dispatcher depends on eventdev
        "dpdk/lib/gpudev",
        "dpdk/lib/gro",
        "dpdk/lib/gso",
        "dpdk/lib/ip_frag",
        "dpdk/lib/jobstats",
        "dpdk/lib/latencystats",
        "dpdk/lib/lpm",
        "dpdk/lib/member",
        "dpdk/lib/pcapng",
        "dpdk/lib/power",
        "dpdk/lib/rawdev",
        "dpdk/lib/regexdev",
        "dpdk/lib/mldev",
        "dpdk/lib/rib",
        "dpdk/lib/reorder",
        "dpdk/lib/sched",
        "dpdk/lib/security",
        "dpdk/lib/stack",
        "dpdk/lib/vhost",
        "dpdk/lib/ipsec", # ipsec lib depends on net, crypto and security
        "dpdk/lib/pdcp", # pdcp lib depends on crypto and security
        "dpdk/lib/fib", #fib lib depends on rib
        "dpdk/lib/port", # pkt framework libs which use other libs from above
        "dpdk/lib/pdump", # pdump lib depends on bpf
        "dpdk/lib/table",
        "dpdk/lib/pipeline",
        "dpdk/lib/graph",
        "dpdk/lib/node",
    ],
    visibility = ["//visibility:public"],
    alwayslink = 1,
    copts = [
        "-mrtm",
        "-D_GNU_SOURCE",
        "-DRTE_EXEC_ENV_LINUX",
        "-mavx512f", "-mavx512dq", "-mavx512bw", "-mavx512vl", "-mavx512ifma",
        "-mavx512er", "-mavx512cd", "-mavx2", "-mavx", "-msse4.2", "-msse4.1",
        "-mvpclmulqdq",
        "-mpclmul",
        "-mcrc32",
        "-std=c11",
        "-Wno-strict-prototypes",
        "-D_BSD_SOURCE",
        "-D_DEFAULT_SOURCE",
        "-D_XOPEN_SOURCE=600",
        # "-Wvisibility",
        "-Wno-address-of-packed-member",
        "-Wno-#pragma-messages",
    ],
)

cc_binary(
    name = "fstack",
    deps = [":lib-nostdinc", ":lib-stdinc", ":dpdk"],
    linkshared = 1,
    visibility = ["//visibility:public"],
)